version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "9090:9090" # gRPC
      - "8080:8080" # gRPC-Web
    environment:
      - GRPC_WEB_HOST=0.0.0.0:8080
      - GRPC_HOST=0.0.0.0:9090

  frontend:
    build: frontend_old
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_GRPC_HOST=http://backend:8080